name: ACMC 2020
tagline: "ACMC2020: Inclusion"
date: July 2020
proceedings_title: "ACMC 2020: Proceedings of the 2020 Australasian Computer Music Conference"
analytics: UA-
logo:
  image: static/images/acmc2020-logo-nobox.png
  width: 180px
  height: auto
# uncomment the following line to show the site title next to the logo image
# site_title: ACMC'20
page_title:
  prefix: "ACMC 2020"
  separator: ': '
background_image: static/images/main.jpg
header_banner: static/images/header-banner-1920.jpg
organization: ACMC Organising Committee
calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: true  #  Include Sunday and Saturday
