name: ACMC 2020
tagline: "ACMC'20: Inclusion"
date: July 2020
proceedings_title: "ACMC 2020: Proceedings of the 2020 Australasian Computer Music Conference"
analytics: UA-
logo:
  image: static/images/acma-logo.png
  width: 180px
  height: auto
# uncomment the following line to show the site title next to the logo image
# site_title: ACMC'20
page_title:
  prefix: "ACMC 2020"
  separator: ': '
background_image: static/images/main.jpg
organization: ACMC Organising Committee
calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: true  #  Include Sunday and Saturday

committee:
  - role: General Chair
    name: Ben Swift
    aff: Australian National University
    tw: benswift
  - role: Inclusion Chair
    name: Nat Grant
    aff:
    tw:
  - role: Paper and Artist Talk Chair
    name: Charles Martin
    aff: Australian National University
    tw: cpmpercussion
  - role: Installation & Visuals Chair
    name: Kit Devine
    aff: Australian National University
    tw:
  - role: Music and Performance Chair
    name: Alexander Hunter
    aff: Australian National University
    tw:
  - role: Local Venues Chair
    name: Sia Ahmad
    aff: Australian National University
    tw:
