name: build & deploy
description: build and deploy the static site to GH pages

on:
  push:
    branches:
      - master

jobs:
  freeze-site:
    name: Create static site with Frozen-Flask
    runs-on: ubuntu-latest
    # built from the Dockerfile in this repo
    container: benswift/acmc:0.1.0

    steps:
    - uses: actions/checkout@v2

    - name: freeze ❄
      run: poetry run make freeze
      working-directory: /app

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      working-directory: /app
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
